version: '3'
services:
  # web:
  #   build: .
  #   ports:
  #   - "9999:8888"

  nginx:
   image: nginx:alpine
   ports:
    - 900:8088
   volumes:
    - ./html:/usr/share/nginx/html
    - ./conf/nginx.conf:/etc/nginx/nginx.conf