version: '3'
services:
  web:
    build: .
    ports:
    - "3000:3000"
    depends_on:
    - mysql
    - redis

  redis:
    image: "redis:alpine"

  nginx:
    image: "nginx:alpine"
    ports:
    - 88:88
    volumes:
    - ./dist:/usr/share/nginx/html
    - ./conf/nginx.conf:/etc/nginx/nginx.conf

  mysql:
    image: mysql:5.6
    environment:
    - MYSQL_ROOT_PASSWORD=123456
